version: '3.7'
services:
  node:
    container_name: cart-project
    build: .
    environment: 
      PORT: 3000
      MONGODB_URI: mongodb://mongo:27017/cart-project
      JWT_SECRET: 2h31g23rh23f
    ports:
      - '3000:3000'
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'